defaults:
  - _base_nerf
  - _self_

training:
  N_rand: 1024
  ft_path: None

rendering:
  N_samples: 64
  N_importance: 64
  raw_noise_std: 1e0

dataset:
  dataset_type: llff
  llff:
    factor: 8
    no_ndc: false
    lindisp: false
    spherify: false
    llffhold: 8
